CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	TIPO ENUM('EMP','FIS') NOT NULL,
	CPF VARCHAR(15) UNIQUE,
	CNPJ VARCHAR(20) UNIQUE,
    SEXO ENUM('M','F')
);
	
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(6) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE SERVICO (
	IDSERVICO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_INIC VARCHAR(12) NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE SETOR (
	IDSETOR INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO_TRAB VARCHAR (50)
);

CREATE TABLE EQUIPE (
	IDEQUIPE INT PRIMARY KEY AUTO_INCREMENT,
	ID_SETOR INT UNIQUE,
	FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (IDSETOR)
);

CREATE TABLE COLABORADOR (
	IDCOLABORADOR INT PRIMARY KEY AUTO_INCREMENT,
	SETOR VARCHAR(50) NOT NULL,
	ID_EQUIPE INT,
	FOREIGN KEY (ID_EQUIPE)
	REFERENCES EQUIPE(IDEQUIPE),
	ID_SERVICO INT,
	FOREIGN KEY (ID_SERVICO)
	REFERENCES SERVICO(IDSERVICO),
	ID_SETOR INT,
	FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR(IDSETOR)
);

CREATE TABLE APTIDAO(
	IDAPTIDAO INT PRIMARY KEY AUTO_INCREMENT,
	APTIDAO_1 VARCHAR(50) NOT NULL,
	APTIDAO_2 VARCHAR(50),
	APTIDAO_3 VARCHAR(50),
	APTIDAO_4 VARCHAR(50),
	ID_COLABORADOR INT UNIQUE,
	FOREIGN KEY (ID_COLABORADOR)
	REFERENCES COLABORADOR(IDCOLABORADOR)
);

INSERT INTO CLIENTE VALUES(NULL,'LILIAN','FIS','12345678951',NULL,'F');
INSERT INTO CLIENTE VALUES(NULL,'JOAO','FIS',12345778251,NULL,'M');
INSERT INTO CLIENTE VALUES(NULL,'INTELBRAS','EMP',NULL,61674757000155,NULL);
INSERT INTO CLIENTE VALUES(NULL,'SULCLEAN','EMP',NULL,56370457000142,NULL);
INSERT INTO CLIENTE VALUES(NULL,'PEDRO','FIS',05976860095,NULL,'M');
INSERT INTO CLIENTE VALUES(NULL,'HENRIQUE','FIS',52591322031,NULL,'M');
INSERT INTO CLIENTE VALUES(NULL,'VINICIUS','FIS',37088675056,NULL,'M');
INSERT INTO CLIENTE VALUES(NULL,'MICROSOFT','EMP',NULL,78338524000184,NULL);

INSERT INTO ENDERECO VALUES(NULL,'SAO SEBASTIAO','300','CENTRO','SANTA MARIA','RS',5);
INSERT INTO ENDERECO VALUES(NULL,'PEDRO CUNHA','200','JUSCELINO KUBITSCHEK','SANTA MARIA','RS',7);
INSERT INTO ENDERECO VALUES(NULL,'JUSCELINO','145','CENTRO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'ANTONIO FERREIRA','204','IGREJINHA','CAPANEMA','PA',4);
INSERT INTO ENDERECO VALUES(NULL,'DOUTOR PEDRO','300','DOM PEDRO','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'PORTUGAL','140','CENTRO','NOVA FRIBURGO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'MARAVILHA','160','MEIER','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'SAO SEBASTIAO','200','CENTRO','AGUDO','RS',2);

INSERT INTO TELEFONE VALUES(NULL,'RES', '998796358',1);
INSERT INTO TELEFONE VALUES(NULL,'COM', '998526471',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL', '996342879',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL', '996314826',4);
INSERT INTO TELEFONE VALUES(NULL,'COM', '995642879',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL', '9935789561',6);
INSERT INTO TELEFONE VALUES(NULL,'RES', '998631578',7);
INSERT INTO TELEFONE VALUES(NULL,'RES', '998751268',8);

INSERT INTO SETOR VALUES (NULL,'ELETRICO');
INSERT INTO SETOR VALUES (NULL,'CONSTRUCAO');
INSERT INTO SETOR VALUES (NULL,'JARDIM');
INSERT INTO EQUIPE VALUES (NULL,1);
INSERT INTO EQUIPE VALUES (NULL,2);
INSERT INTO EQUIPE VALUES (NULL,3);

INSERT INTO SERVICO VALUES (NULL,'22/03/2020','JARDINAGEM',5);
INSERT INTO SERVICO VALUES (NULL,'22/03/2020','CONSTRUCAO',5);
INSERT INTO SERVICO VALUES (NULL,'18/04/2019','JARDINAGEM',2);
INSERT INTO SERVICO VALUES (NULL,'08/01/2021','ELETRICO',1);
INSERT INTO SERVICO VALUES (NULL,'14/08/2017','CONSTRUCAO',6);
INSERT INTO SERVICO VALUES (NULL,'19/12/2016','ELETRICO',8);
INSERT INTO SERVICO VALUES (NULL,'19/12/2016','CONSTRUCAO',8);
INSERT INTO SERVICO VALUES (NULL,'22/03/2020','JARDINAGEM',1);
INSERT INTO SERVICO VALUES (NULL,'01/10/2015','JARDINAGEM',7);
INSERT INTO SERVICO VALUES (NULL,'05/11/2018','CONSTRUCAO',3);

INSERT INTO COLABORADOR VALUES (NULL,'CORTADORES DE GRAMA',3,1,3);
INSERT INTO COLABORADOR VALUES (NULL,'ELETRICISTAS',1,4,1);
INSERT INTO COLABORADOR VALUES (NULL,'MARCENEIROS',2,1,2);
INSERT INTO COLABORADOR VALUES (NULL,'PEDREIROS',2,5,2);
INSERT INTO COLABORADOR VALUES (NULL,'LIMPADORES DE PISCINA',3,8,3);
INSERT INTO COLABORADOR VALUES (NULL,'JARDINEIRO',3,9,3);
INSERT INTO COLABORADOR VALUES (NULL,'ELETRICISTAS',1,6,1);
INSERT INTO COLABORADOR VALUES (NULL,'LIMPADORES DE PISCINA',3,2,3);
INSERT INTO COLABORADOR VALUES (NULL,'MARCENEIROS',3,7,3);
INSERT INTO COLABORADOR VALUES (NULL,'PEDREIROS',3,10,3);

INSERT INTO APTIDAO VALUES (NULL,'CONHECIMENTO EM PLANTAS','CONHECIMENTO QUIMICO',NULL,NULL,1); 
INSERT INTO APTIDAO VALUES (NULL,'ENGENHEIRO ELETRICO',NULL,NULL,NULL,2);
INSERT INTO APTIDAO VALUES (NULL,'MADEIREIRO','CORTAR ÁRVORES','EXPERIENCIA COM FERRAMENTAS',NULL,3);
INSERT INTO APTIDAO VALUES (NULL,'MESTRE DE OBRAS',NULL,NULL,NULL,4);
INSERT INTO APTIDAO VALUES (NULL,'CONHECIMENTO QUIMICO',NULL,NULL,NULL,5);
INSERT INTO APTIDAO VALUES (NULL,'BOTANICO','ENTOMOLOGIA',NULL,NULL,6);
INSERT INTO APTIDAO VALUES (NULL,'ENGENHEIRO ELETRICO',NULL,NULL,NULL,7);
INSERT INTO APTIDAO VALUES (NULL,'QUIMICO','HERBALISTA',NULL,NULL,8);
INSERT INTO APTIDAO VALUES (NULL,'ARQUITETO','URBANISTA','PAISAGISTA',NULL,9);
INSERT INTO APTIDAO VALUES (NULL,'ENGENHEIRO CIVIL','UBER','SERVENTE DE PEDREIRO',NULL,10);
